	tilepal 0, GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, RED
	tilepal 0, RED, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, WATER, GREEN, BROWN, BROWN
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, GREEN, GRAY, GRAY
	tilepal 0, WATER, YELLOW, BROWN, BROWN, GRAY, BROWN, GRAY, YELLOW
	tilepal 0, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN, ROOF, ROOF
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, ROOF, GRAY
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, GREEN, GREEN, ROOF, ROOF
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GREEN, GREEN, ROOF, ROOF
	tilepal 0, ROOF, ROOF, WATER, BROWN, GRAY, ROOF, ROOF, WATER
	tilepal 0, WATER, ROOF, ROOF, ROOF, GREEN, GREEN, ROOF, ROOF

rept 16
	db $ff
endr

	tilepal 1, ROOF, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, RED, GREEN, RED, BROWN, BROWN
	tilepal 1, BROWN, BROWN, RED, BROWN, BROWN, BROWN, ROOF, BROWN
	tilepal 1, BROWN, ROOF, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GRAY, BROWN, BROWN, GRAY, ROOF, ROOF
	tilepal 1, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, GRAY, GREEN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF, ROOF
	tilepal 1, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, RED, BROWN
	tilepal 1, GREEN, GREEN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
