	tilepal 0, GRAY, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, GRAY, WATER, GRAY, WATER, WATER, WATER, RED, RED
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, RED, RED, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, RED, WATER
	tilepal 0, YELLOW, YELLOW, WATER, WATER, GRAY, RED, RED, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 0, GREEN, GREEN, WATER, WATER, GRAY, GRAY, GRAY, YELLOW

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, WATER, RED, RED, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, RED, RED, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, RED, RED, GRAY, GRAY, RED, RED, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, GREEN, GREEN
	tilepal 1, WATER, RED, WATER, BROWN, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, GREEN, GREEN
	tilepal 1, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, BROWN
	tilepal 1, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
